name = "Aeronautics Server Modpack"
author = "Michael"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf61abfea0306e428c68d7f9888fb060dbc696fc6120ab5da85524c2f9d72776"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
