name = "Aeronautics Server Modpack"
author = "Michael"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3c66e5356c211dd98c7e410d9a4c68fdba91eb57f81b9bf803951835569887b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
