name = "Aeronautics Server Modpack"
author = "Michael"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d0ea97f436151951480ece01dfcda944d9b112424a537758f9f7d37200f85fe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
